### PR TITLE
Escaping m_StatsDictionary illegal properties in regexp way.

### PR DESCRIPTION
**Pull request by Pt-Djefferson**

### CODE REVIEW

**Comment by FINDarkside** [comment]
Sorry, but I'm kinda still unsure what benefit are you trying to gain with this? With the old way, we could actually deserialize the stuff instead of just cutting it away.

**Comment by FINDarkside** [comment]
To be honest I'm not sure if this is a good idea. I'm skeptical if this regex will work in all scenarios and given that the old code should work just fine I'm probably not going to merge this.

**Comment by Pt-Djefferson** [comment]
As you wish. But it will work in all scenarios.

**Comment by FINDarkside** [comment]
Hmm, you're probably correct. I misremembered how the old code worked, it wouldn't work in the scenarios I was thinking either.

**Pull request merged**
