### PR TITLE
Update for latest save system.

### PR DESCRIPTION
**Pull request by MostHostLA**
Note that the path of the save files is locked into the Survival folder.

Wintermute save files tend to fail to load.

Base64 Compression decoding/encoding to read and save files. About/Contributor fix. Material Icon Changes. Packages bump. Version Increment.

Will add secondary sub-folder selector to allow changing it this xmas.

### CODE REVIEW

**Comment by J3ekir** [comment]
Looks like it works fine on build `2.24 126227 S`. Thanks for the changes. Considering the owner has commits since this PR opened, he doesn't care it anymore. I think you should publish a release on your fork.

**Comment by FINDarkside** [comment]
Sorry forgot about this, I can take a look this week.

**Comment by FINDarkside** [comment]
Ok sorry I don't really have the time this weekend. I'll try to do it soon. Obviously you can publish this yourself as well if you want.

**Comment by MostHostLA** [comment]
I'm so packed with work I haven't even been able to make the edits I thought I'd be able to make on Xmas... not really planning on publishing this tbh.
People capable of building from source aren't going to ask questions - leeches will. Don't have the overhead for that myself unfortunately.

**Comment by J3ekir** [comment]
It's not perfect but it opens and works in a way. It shows the new items. You can't add them from thin air but if you have them you can change their condition, amount etc. Considering the original release is not working with the current _(I actually don't know the current, I can check it but it doesn't matter. After they "stopped" working on episode 5 and tried to make more money -probably because of Epic Games deal- they lost my respect. I don't have the DLC on my Steam account.)_ version. At least with my version which is 2.25. That's why I asked you to put a release so people who wants to use the project can use it even if it's not perfect.

I don't know how the program works exactly but I think if you put new items in Resources.resx you can add them with "add item" button too. I would try but I don't think I know C# well enough to understand and edit this. Also I don't know the item's keys. I only know the ones I have. Wiki has some but some of them are different than the ones I have. So the guy who wrote them probably made them up. For example wires are GEAR_WireBundle according to the program but the wiki says GAMEPLAY_Wires.

The last time I played the game was the release of episode 4. I believe the main change you made is adding survival into the path thing. If so, @FINDarkside can add it easily.

**Comment by MostHostLA** [comment]
To pull the correct names and stuff you have to learn how to use Melon Loader, load up the latest game with custom hooks to print out the current strings of stuff - the game is Unity btw, not Epic, so Idk what epic has to do with any of it. 

Usually, you don't just make stuff up, you need to read it off something. Any time they push a new version things change, which is why upkeep and maintenance of something like this is a problem (also why I didn't bother setting new stuff up, with the game still getting updates the codes and items are almost continuously changing between releases).

There's a ton of new maps that would have to be sourced and added too since the original version is rather dated. new locations like different basements/houses that were not part of the game originally. new feats, new health statuses etc.
To properly pull and correct everything to where this is fully functional would take about a week worth of work.

If someone has the free time to undertake the effort, pull the repo, make a new txt file, start listing the new item codes by printing/reading them off melon loader's bash.
But I don't think there's a community of people that would be interested in doing any of that tbth.

**Comment by FINDarkside** [comment]
Yeah to be honest if someone wants to spend a lot of effort on save editor, it might be a better bet to work on the [TypeScript + Vue](https://github.com/FINDarkside/TLD-Save-Editor-3) based editor instead. If the stack is comfortable. 

I actually set up a workflow for that where I could automatically decompile the game + generate save format TS types automatically. But that stopped working when they switched to il2cpp. Also, that was the only interesting part of the project in addition to the save file parsing helpers I coded, so after those were done I lost my interest in the project 😄

**Comment by FINDarkside** [comment]
Thanks for the update! Noticed that the backups button leads to the wrong folder now, but I'll fix that after merging. I'll release it later today.

**Comment by FINDarkside** [comment]
It's released now:

* https://github.com/FINDarkside/TLD-Save-Editor/releases/tag/2.19
* https://www.moddb.com/mods/the-long-dark-save-editor-2/downloads/tld-save-editor-219-v227

**Pull request merged**
